### ISSUE TITLE
Memo doesn't work

### ISSUE THREAD

**Issue by coolassassin** [raveclassic/injectable-ts#14]
Hello!

If you will open this component, you will see the React.memo here, on the line 12:
https://github.com/raveclassic/injectable-ts/blob/main/packages/react/src/dependencies-provider.tsx#L12

But, you can see that this component has `children` prop in props.
Children is a prop which contain JSX inside brackets like so:
```
<DependeciesProvider><span>Some content</span></DependenciesProvider>
```

This JSX will be transformed to:
```
React.createElement(
  'span',
  {},
  'Some content'
)
```

And then this function will return new object on each render.
It means that children for this component will be an object or an array of objects which will be different every single render. That is why this memoization will never work, instead of case when someone decide to memoize these children, but it is crazy one case.
So, you can remove this memo with no worries and it will gain the performance. It is very tiny update, but I want to mention this to make it clear.

**Comment by raveclassic** [comment]
@coolassassin thanks for pointing out!
Yeah, `memo` everywhere is just my OCD :D 
Performance impact is so negligible that it's just "easier" to put it everywhere.
